# Generated by Django 4.2.1 on 2024-04-14 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('tariff', models.DecimalField(decimal_places=2, max_digits=6)),
                ('meter_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utility_type', models.CharField(choices=[('gas', 'газ'), ('svet', 'свет'), ('voda', 'вода')], max_length=20)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
